// <auto-generated />
using System;
using Komis.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Komis.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190327125212_CarEdited")]
    partial class CarEdited
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Komis.Core.Models.Car", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Capacity");

                    b.Property<string>("Description");

                    b.Property<string>("FuelType");

                    b.Property<bool>("IsCarOfTheWeek");

                    b.Property<bool>("IsInACentral");

                    b.Property<string>("Milage");

                    b.Property<string>("Model");

                    b.Property<string>("PictureURL");

                    b.Property<string>("Power");

                    b.Property<decimal>("Price");

                    b.Property<string>("ThumbnailURL");

                    b.Property<int>("YearOfProduction");

                    b.HasKey("ID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Komis.Core.Models.Opinion", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<bool>("WaitingForAnAnswer");

                    b.HasKey("ID");

                    b.ToTable("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
